### ISSUE TITLE
REQUEST: trapezoidal loadings

### ISSUE THREAD

**Issue by Charles-Rhinoforyou** [karamba3d/K3D_NightlyBuilds#10]
Would it be possible to add the trapezoidal loadings on the beams?

Today only linearly distributed loads or point loads are available on beams.

![image](https://user-images.githubusercontent.com/9198859/97779034-cbdb3400-1b7b-11eb-8dd8-fb3ea3fa8570.png)

**Comment by karamba3d** [comment]
Dear Sicambre158,

implementing new types of beam-loads will happen within the next few weeks.

Please check the nightly-builds of version 2.0.0.

best regards,
Clemens Preisinger
cp@karamba3d.com<mailto:cp@karamba3d.com>


Karamba3D
Clemens Preisinger
A-1010 Vienna
www.karamba3d.com<https://www.karamba3d.com>
LinkedIn<https://www.linkedin.com/company/karamba3d> | Instagram<https://www.instagram.com/karamba3d/> | Youtube<https://www.youtube.com/c/karamba3d>


________________________________

**Comment by Charles-Rhinoforyou** [comment]
> Please check the nightly-builds of version 2.0.0.

Thank you very much !

**Comment by karamba3d** [comment]
Dear @Charles-Rhinoforyou,
the new WIP version of Karamba3D 2.0.0 contains distributed, trapezoidal loads. See https://github.com/karamba3d/K3D_NightlyBuilds/releases.
-- Clemens
