### ISSUE TITLE
REQUEST: length and forces units settings

### ISSUE THREAD

**Issue by Charles-Rhinoforyou** [karamba3d/K3D_NightlyBuilds#13]
Would it be possible to allow the change of length and forces units settings (for example mm instead of m, daN instead of kN) in future versions of Karamba

**Comment by Clemens-Preisinger** [comment]
I will put this feature on my TODO-list. I think the best way to do it would be to have entries Karamba.ini-file which allow one to set the units for input-.geometry, forces, moments, stresses, displacements,...
-- Clemens

**Comment by karamba3d** [comment]
in Karamba3D 2.0.0_201127_WIP (see https://github.com/karamba3d/K3D_NightlyBuilds/releases) physical units can be changed by the user via the 'karamba.ini'-file in the Karamba3D installation directory. The 'Settings'-component additionally allows to set the physical unit of input geometry.
-- Clemens
