### ISSUE TITLE
BUG: Non-Linear Analysis component crashes with membrane shell elements

### ISSUE THREAD

**Issue by Vigardo** [karamba3d/K3D_NightlyBuilds#19]
Hi! Clemens told me to file here a bug report for Karamba3D 2.0.0_201020 WIP (https://github.com/karamba3d/K3D_NightlyBuilds/releases/tag/2.0.0_201020). Please, check https://discourse.mcneel.com/t/how-to-model-a-membrane-in-karamba/112602/5 for more info and the attached GH sketch.

I´ve set False the Bending input of the MeshToShell component (in Materials Cross-Section group) to test your brand new membrane finite elements. Unfortunately, the Non-Linear component crashes and complains with the following error (with all solution procedures):

[“1. Unknown error occurred while solving for the structural response of the system. May cause errors in exported models.”]

The Large Deformation component also crashes, but with a different error:

[“1. Could not calculate deformed model. Use the component ‘Analyze’ to get details.”]

The Analyze component says:

[“1. There are 6 rigid body modes in the system. This means some parts can move freely without causing deformation. Try to use the ‘Eigen Modes’-component and activate the display of local coordinate axes: The first eigen-mode will be the rigid body motion. If this does not help, check whether you have a pinned support directly attached to a hinge. A hinge introduces an extra node which may cause the problem. When analyzing a flat shell structure one has to lock the rotation perpendicular to the plate in at least one node.”]

Accordingly, I´ve checked the normal modes and the membrane blows out above and below the triangle plane…

By the way, I can´t adequately visualize the normal modes (with Bending of shell elements set to True). I can only visualize something if I set the Result-Case from Model View component to number 4… but I haven´t used Load Cases yet…

[Membrane2.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/5610511/Membrane2.zip)

**Comment by Clemens-Preisinger** [comment]
Hi @Vigardo,
the issue should be solved in the current WIP build 'Karamba3D 2.0.0_201211 WIP'.
-- Clemens
