### ISSUE TITLE
BUG: Rhino crashes on Natural Vibration Analysis with Joints

### ISSUE THREAD

**Issue by robertvier** [karamba3d/K3D_NightlyBuilds#20]
**Describe the bug**
The Nat.Vib. component turns red, then after a few seconds Rhino crashes.

**To Reproduce**
Open my example file.

**Notes**
The bug only seems to happen if there are loads defined in the model
[debug.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/5621845/debug.zip)

**Comment by Clemens-Preisinger** [comment]
Done. The problem was an outdated dll in the installer.
