### ISSUE TITLE
Cross section design according to EC3: make use of gammaM0 and gammaM1 dependent on the axial normal force

### ISSUE THREAD

**Issue by Clemens-Preisinger** [karamba3d/K3D_NightlyBuilds#29]
currently (version 1.3.3) gamma_m1 is used to reduce NRd, MyRd and MzRd in case the buckling length in the corresponding direction is different from zero:
if (lk_y != 0) My_Rd /= gamma_m1_; else My_Rd /= gamma_m0_;
if (lk_z != 0) Mz_Rd /= gamma_m1_; else Mz_Rd /= gamma_m0_;
if (lk_z != 0 || lk_y != 0) N_Rd /= gamma_m1_; else N_Rd /= gamma_m0_;
So it is not dependent on whether the normal force is tensile or compressive. This is a simplification which speeds up calculation in case of several load-cases. it would be a good idea to change this in the next release.

**Comment by karamba3d** [comment]
This simplification has been abandoned in 'Karamba3D 2.0.0_210504_WIP. Now gamma_m is chosen according to whether the normal force is compressive or tensile.
