### ISSUE TITLE
BUG: Beam Joint Agent - toGeometry 'Pt' creates joint always on beam start, not at Pt-location

### ISSUE THREAD

**Issue by robertvier** [karamba3d/K3D_NightlyBuilds#30]
**Describe the bug**
The Position of joints is not set correctly. Instead of placing the joint at the end of the beam where the reference point geometry is located, the joint always gets placed on the start of the beam.

**Comment by karamba3d** [comment]
Thanks for your bug report!
This problem is solved in Karamba 2.0.0_210212_WIP.
-- Clemens
