### ISSUE TITLE
BUG: Shell Section Component loads default values but shows custom values

### ISSUE THREAD

**Issue by robertvier** [karamba3d/K3D_NightlyBuilds#31]
**Describe the bug**
On opening a file, or copy-pasting a Shell-Section component, any values that have been modified before (sliders, checkboxes of the UI) are shown correctly, but internally the component seems to use the default values. One needs to manipulate the values so they are updated.

**Comment by EnricoAntolini** [comment]
Hello Robert, 
Could you send me the .gha file with the bug? 
Thanks

Kd,
Enrico

**Comment by robertvier** [comment]
Hi Enrico,

the bug happens at every use of the component for me. Attached is a file. I am using Rhino 7.

[kr]

(url)
[debug shell sections.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/5970402/debug.shell.sections.zip)

**Comment by karamba3d** [comment]
The problem is solved in the next nightly build.
