### ISSUE TITLE
REQUEST: add a volumetric BESO

### ISSUE THREAD

**Issue by rudiwave** [karamba3d/K3D_NightlyBuilds#32]
Currently the BESO algorithm works with beams and shells - it would be great if it worked with mesh volumes as well! The referenced method "X. Huang and M. Xie. Evolutionary Topology Optimization of Continuum Structures: Methods and Applications. Wiley, 2010" seems to work with volumes as well.

**Comment by karamba3d** [comment]
Hello @rudiwave,
at the moment (Karamba3D 1.3.3.) there are no volumetric elements available in Karamba3D. It is planned however to implement them in the future. Once this has been done the BESO algorithm will be generalized to volumetric elements.
-- Clemens

**Comment by rudiwave** [comment]
> It is planned however to implement them in the future. 
> 
Wunderbar, freue mich schon sehr darauf! Noch eine kleine Frage: wie würde Karamba dann diese volumetrischen Elemente handhaben? Würde das mit einem Voxel-artigen Ansatz gelöst werden? Denn soweit ich weis unterstützt Rhino/Grasshopper keine echten volumetrischen Meshes (Tetraeder-Meshes z.B.).

Wünsche dem Team bestes Gelingen! Karamba ist wirklich eine geniale Software - durch das schnelle Feedback und Anpassbarkeit bekommt man wirklich ein neues Gefühl für statische Probleme… ich liebe es.

Und noch eine kleine Sache: Ich habe eh schon im Forum gelesen, dass an der Mac Version von Karamba mit dem 2.0 Release gearbeitet wird, wollte dennoch noch mal sagen, dass ich kaum darauf warten kann und mich schon sehr freue, die erste Beta einmal testen zu können! 

LG aus Stuttgart,

Rudi

**Comment by karamba3d** [comment]
Hallo Rudi,

danke für dein Interesse an Karamba3D!

ich denke es werden normale FE-Tetraedereelemente werden. Für Volumina gibt es ganz gute Tetraeder-Mesher als open source - ich habe sie aber noch nicht ausprobiert.

Die MAC Version ist in Planung - es gibt halt Features (wie. z.B. Lastfallüberlagerung) die ich wegen der begrenzten Resourcen vorziehen muss.

Viele Grüße,
Clemens
cp@karamba3d.com<mailto:cp@karamba3d.com>


Karamba3D
Clemens Preisinger
A-1010 Vienna
www.karamba3d.com<https://www.karamba3d.com>
LinkedIn<https://www.linkedin.com/company/karamba3d> | Instagram<https://www.instagram.com/karamba3d/> | Youtube<https://www.youtube.com/c/karamba3d>


________________________________
