### ISSUE TITLE
BUG: Arclength Method: support loads are by a factor of exactly 2 too large 

### ISSUE THREAD

**Issue by Clemens-Preisinger** [karamba3d/K3D_NightlyBuilds#33]
In the attached file the support reactions are by a factor of 2 too large. See also https://discourse.mcneel.com/t/nonlinear-arclength-solver-amplitude-of-vertical-reaction-is-exactly-the-double-of-the-applied-vertical-load/119396

**Comment by karamba3d** [comment]
The bug is connected to the way how the elastic energy is calculated in Karamba3D. It will be solved in the course of a refacturing of the elastic energy calculation.

**Comment by Clemens-Preisinger** [comment]
The bug is fixed in Karamba3D 2.2.0
