### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by Marco-Pellegrino** [karamba3d/K3D_NightlyBuilds#45]
**Describe the bug**

Hi @karamba3d.

I think I have just found a bug or, it would be great to change the behaviour of the assemble regarding the mass.
Apparently, it is not possible to have more than one Point Mass in the same point.

i.e.
If I have a series of point Mass in the same point and the latest has mass == 0, then it is like if the structure does not have any point mass at all.

Probably the assemble is not keeping track of the points but just using the latest?  

![image](https://user-images.githubusercontent.com/53620289/136205789-de9726ff-13cd-4682-b24b-e572941110f2.png)

Best,
Marco

**Comment by Marco-Pellegrino** [comment]
Hi @Clemens-Preisinger! 

Is this still a bug or it has been resolved?
I am asking because, in the roadmap, it is resolved but I can not see if the bug has been resolved in any of the new release description 😊

**Comment by Clemens-Preisinger** [comment]
Hi @Marco-Pellegrino,
the behavior is changed in the current release. Sorry, I forgot to mention it in the change-log.
-- Clemens
