### ISSUE TITLE
BUG: Node Forces

### ISSUE THREAD

**Issue by Marco-Pellegrino** [karamba3d/K3D_NightlyBuilds#46]
Hi @karamba3d 

I am currently using Karamba 2.2.0.6 and I am not sure that **node forces** outputs for Forces and Moments is following the right data tree.
Is the data tree going to follow the same Dir tree?

![image](https://user-images.githubusercontent.com/53620289/141779518-d687cd78-86d8-4864-94c3-75599a8480bf.png)

**Comment by Clemens-Preisinger** [comment]
Thanks for the bug report!
The bug is fixed in Karamba3D 2.2.0.7.
-- Clemens
