### ISSUE TITLE
Support Position Output as a plane instead of Point

### ISSUE THREAD

**Issue by Marco-Pellegrino** [karamba3d/K3D_NightlyBuilds#48]
Hi @karamba3d 

I am wondering if it would make sense to have a plane output in the reaction forces components.

I think that **Pos** should be the **local plane** instead of a simple Point object. It would also make easier to see the reaction forces.

![image](https://user-images.githubusercontent.com/53620289/142421989-f0b314c6-e4c9-4dc1-8ce4-9f8ca5dd739a.png)

**Comment by Clemens-Preisinger** [comment]
Hi Marco,
thanks for your suggestion. That's a good point! I will add this.
-- Clemens
