### ISSUE TITLE
Add option to render model symbols via GH display pipeline

### ISSUE THREAD

**Issue by Clemens-Preisinger** [karamba3d/K3D_NightlyBuilds#5]
Symbols for loads, supports, joints and number output are currently rendered directly to the Rhino view-port. This is a problem for third party use (e.g. Shapediver).

It would be useful to have an option in the karamba.ini-file to switch between the existing mode and direct mode where the geometry is output at an new output-plug (e.g. 'Symbols') of the ModelView-component

**Comment by karamba3d** [comment]
Is implemented in Karamba3D 2.0.0_210504_WIP: go to karamba.ini and set 'with_parametric_user_interface = true', then a toolbar section will appear in the Karamba3D-toolbar with components for rendering K3D symbols in the Rhino viewport.
