### ISSUE TITLE
BUG: Warning vanished from reaction forces component when you have duplicate supports

### ISSUE THREAD

**Issue by jjsolly** [karamba3d/K3D_NightlyBuilds#51]
Looking at a model just now we realised we had duplicated some supports i.e. had two sets of points that supports were created from and a few points existed in both sets. This was not deliberate. 

The loads per support appear correct (so assume the model has correctly noted these are 1 support in 1 location) but they are reported by the "Reaction Forces" component multiple times and also therefore the sum of forces is incorrect. I think there used to be a warning raised when you did this but that warning now appears to be gone. It would be great for checking purposes if that warning was put back.

**Comment by Clemens-Preisinger** [comment]
Thanks for the comment! I will add the warning again for the case that multiple supports are supplied at the same node and support DOFs get defined more than once.

**Comment by Clemens-Preisinger** [comment]
The warning is now again active.
