### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by mutenroch** [karamba3d/K3D_NightlyBuilds#62]
lineToBeam doesn't work on one particular lines list with no special characteristics. The list include different lengths lines, most of them repeated, some of them are converted to beams correctly, some of the are not, even with the same length.

In the attached file the example is replicated with another test curves list and everything is fine.

Please take a look on it.

Thanks
![Captura](https://user-images.githubusercontent.com/10659481/222736263-0c89daf7-128a-4bf1-a38a-a4387f18ef96.JPG)

[KARAMBA MODEL ISSUE.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/10882422/KARAMBA.MODEL.ISSUE.zip)

**Comment by mutenroch** [comment]
Well, it seems that after subdividing a line, some of the segments are recognized as "line-like curve" and a few as "linear curve". Well, the later are not converted to beams with lineToBeam component apparently which is likely  annoying.

**Comment by Clemens-Preisinger** [comment]
Thanks for the bug report! I will fix that for the next service release.

**Comment by Clemens-Preisinger** [comment]
The bug is fixed in version 2.2.0.18.
