### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by jjsolly** [karamba3d/K3D_NightlyBuilds#8]
**Describe the bug**
I think the newest WIP installer for 200914 is actually installing version 200725 still. 

**To Reproduce**
Try installing latest version

**Notes**
I uninstalled everything then installed latest installer. This is what canvas now shows
![2020-10-11 19_29_05-Grasshopper - unnamed](https://user-images.githubusercontent.com/13330147/95686786-1eb67100-0bf8-11eb-865b-2b45f0d664ce.png)

**Comment by Clemens-Preisinger** [comment]
Thanks for the error report. I did not updated the build number correctly. In the current build the issue is solved.
-- Clemens
